-- ============================================================================
-- สถานที่ส่งข้าวห่อ (ข้อมูลกลางสำหรับทุกเครื่อง)
--
--   READ          ผู้ใช้ทั่วไปและแอดมินอ่านรายการของโครงการได้
--   CREATE/UPDATE/DELETE  ทำผ่าน RPC ที่ตรวจ PIN แอดมินจาก app_config เท่านั้น
--
-- ประวัติ food_orders เก็บชื่อสถานที่เป็นข้อความ จึงไม่ถูกเปลี่ยนหรือลบตาม
-- การแก้ไขรายการตั้งค่านี้
--
-- รันหลัง 01–10 (รันซ้ำได้)
-- ============================================================================

create table if not exists public.delivery_points (
  id bigint generated by default as identity primary key,
  project text not null,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint delivery_points_project_name_key unique (project, name),
  constraint delivery_points_project_not_blank check (btrim(project) <> ''),
  constraint delivery_points_name_not_blank check (btrim(name) <> ''),
  constraint delivery_points_name_length check (char_length(btrim(name)) <= 80)
);

comment on table public.delivery_points is 'รายการสถานที่ส่งข้าวห่อที่แอดมินโรงครัวจัดการ แยกตามโครงการ';
comment on column public.delivery_points.name is 'ชื่อที่แสดงในช่อง ส่งห่อที่; การเปลี่ยนชื่อไม่กระทบ food_orders ย้อนหลัง';

create unique index if not exists delivery_points_project_name_ci_key
  on public.delivery_points (project, lower(btrim(name)));

create index if not exists delivery_points_project_sort_idx
  on public.delivery_points (project, sort_order, id);

alter table public.delivery_points enable row level security;

drop policy if exists delivery_points_read on public.delivery_points;
create policy delivery_points_read
  on public.delivery_points
  for select
  to anon, authenticated
  using (true);

revoke all on public.delivery_points from anon, authenticated;
grant select (id, project, name, sort_order, created_at, updated_at)
  on public.delivery_points to anon, authenticated;

-- ---------------------------------------------------------------------------
-- รายการเริ่มต้นของทั้ง 2 โครงการ
-- ---------------------------------------------------------------------------
with seed(project, name, sort_order) as (
  values
    ('xepon',  'KeepRoom ตู้เหลือง', 10),
    ('xepon',  'KeepRoom ตู้ขาว',    20),
    ('xepon',  'หน้างาน',             30),
    ('xepon',  'แคมป์ที่พัก',          40),
    ('sekong', 'KeepRoom ตู้เหลือง', 10),
    ('sekong', 'KeepRoom ตู้ขาว',    20),
    ('sekong', 'หน้างาน',             30),
    ('sekong', 'แคมป์ที่พัก',          40)
)
insert into public.delivery_points (project, name, sort_order)
select seed.project, seed.name, seed.sort_order
  from seed
 where not exists (
   select 1
     from public.delivery_points current
    where current.project = seed.project
      and lower(btrim(current.name)) = lower(btrim(seed.name))
 );

-- ---------------------------------------------------------------------------
-- เพิ่มสถานที่ส่ง
-- ---------------------------------------------------------------------------
create or replace function public.create_delivery_point(
  p_project text,
  p_name text,
  p_admin_pin text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_project text := lower(btrim(coalesce(p_project, '')));
  v_name text := btrim(coalesce(p_name, ''));
  v_admin_pin text;
  v_sort_order integer;
  v_row public.delivery_points;
begin
  select value into v_admin_pin from public.app_config where key = 'admin_pin';
  if v_admin_pin is null or coalesce(p_admin_pin, '') <> v_admin_pin then
    raise exception 'รหัสแอดมินไม่ถูกต้อง';
  end if;
  if v_project = '' then
    raise exception 'กรุณาระบุโครงการ';
  end if;
  if v_name = '' then
    raise exception 'กรุณากรอกชื่อสถานที่ส่ง';
  end if;
  if char_length(v_name) > 80 then
    raise exception 'ชื่อสถานที่ส่งต้องไม่เกิน 80 ตัวอักษร';
  end if;
  if exists (
    select 1 from public.delivery_points
     where project = v_project and lower(btrim(name)) = lower(v_name)
  ) then
    raise exception 'มีสถานที่ส่ง % อยู่ในรายการแล้ว', v_name;
  end if;

  select coalesce(max(sort_order), 0) + 10
    into v_sort_order
    from public.delivery_points
   where project = v_project;

  insert into public.delivery_points (project, name, sort_order)
  values (v_project, v_name, v_sort_order)
  returning * into v_row;

  return to_jsonb(v_row);
end;
$$;

-- ---------------------------------------------------------------------------
-- เปลี่ยนชื่อสถานที่ส่ง — ไม่แก้ food_orders ย้อนหลัง
-- ---------------------------------------------------------------------------
create or replace function public.rename_delivery_point(
  p_project text,
  p_current_name text,
  p_new_name text,
  p_admin_pin text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_project text := lower(btrim(coalesce(p_project, '')));
  v_current_name text := btrim(coalesce(p_current_name, ''));
  v_new_name text := btrim(coalesce(p_new_name, ''));
  v_admin_pin text;
  v_id bigint;
  v_row public.delivery_points;
begin
  select value into v_admin_pin from public.app_config where key = 'admin_pin';
  if v_admin_pin is null or coalesce(p_admin_pin, '') <> v_admin_pin then
    raise exception 'รหัสแอดมินไม่ถูกต้อง';
  end if;
  if v_project = '' or v_current_name = '' then
    raise exception 'กรุณาระบุโครงการและสถานที่เดิม';
  end if;
  if v_new_name = '' then
    raise exception 'กรุณากรอกชื่อสถานที่ส่งใหม่';
  end if;
  if char_length(v_new_name) > 80 then
    raise exception 'ชื่อสถานที่ส่งต้องไม่เกิน 80 ตัวอักษร';
  end if;

  select id into v_id
    from public.delivery_points
   where project = v_project
     and lower(btrim(name)) = lower(v_current_name);

  if v_id is null then
    raise exception 'ไม่พบสถานที่ส่ง %', v_current_name;
  end if;
  if exists (
    select 1 from public.delivery_points
     where project = v_project
       and lower(btrim(name)) = lower(v_new_name)
       and id <> v_id
  ) then
    raise exception 'มีสถานที่ส่ง % อยู่ในรายการแล้ว', v_new_name;
  end if;

  update public.delivery_points
     set name = v_new_name, updated_at = now()
   where id = v_id
  returning * into v_row;

  return to_jsonb(v_row);
end;
$$;

-- ---------------------------------------------------------------------------
-- ลบสถานที่ส่ง — ไม่ลบหรือแก้ food_orders ย้อนหลัง
-- ---------------------------------------------------------------------------
create or replace function public.delete_delivery_point(
  p_project text,
  p_name text,
  p_admin_pin text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_project text := lower(btrim(coalesce(p_project, '')));
  v_name text := btrim(coalesce(p_name, ''));
  v_admin_pin text;
  v_deleted integer;
begin
  select value into v_admin_pin from public.app_config where key = 'admin_pin';
  if v_admin_pin is null or coalesce(p_admin_pin, '') <> v_admin_pin then
    raise exception 'รหัสแอดมินไม่ถูกต้อง';
  end if;
  if v_project = '' or v_name = '' then
    raise exception 'กรุณาระบุโครงการและสถานที่ส่ง';
  end if;

  delete from public.delivery_points
   where project = v_project
     and lower(btrim(name)) = lower(v_name);
  get diagnostics v_deleted = row_count;

  if v_deleted = 0 then
    raise exception 'ไม่พบสถานที่ส่ง %', v_name;
  end if;

  return jsonb_build_object(
    'project', v_project,
    'name', v_name,
    'deleted', v_deleted
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- สิทธิ์เรียก RPC
-- ---------------------------------------------------------------------------
revoke all on function public.create_delivery_point(text, text, text) from public;
revoke all on function public.rename_delivery_point(text, text, text, text) from public;
revoke all on function public.delete_delivery_point(text, text, text) from public;

grant execute on function public.create_delivery_point(text, text, text) to anon, authenticated;
grant execute on function public.rename_delivery_point(text, text, text, text) to anon, authenticated;
grant execute on function public.delete_delivery_point(text, text, text) to anon, authenticated;

-- ตรวจผล
select project, name, sort_order
  from public.delivery_points
 order by project, sort_order, id;
